config/routes.rb
Rails.application.routes.draw do
  get 'cart_items/index'
  devise_for :customers
  devise_for :admins
  namespace :admins do
  	root 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :item_genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items
  resources :customers, only: [:show, :edit, :update, :exit, :destroy] 
  resources :shipping_addresses, only:[:index, :edit, :update, :destroy]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shipping_addresses, dependent: :destroy

  validates :address, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_number, presence: true
  validates :phone_number, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :item_genre
  attachment :image

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :item_genre_id, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: { in: [true, false] }
end

app/models/item_genre.rb
class ItemGenre < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  #真偽値の存在をチェックしたい場合には以下を記述
  validates :is_delete, inclusion: { in: [true, false] }

  has_many :items
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  def index
  	@customers = Customer.all
  end

  def show
  	@customer = Customer.find(params[:id])
  end

  def edit
  	@customer = Customer.find(params[:id])
  end

  def update
  	@customer = Customer.find(params[:id])
  	if @customer.update(customer_params)
   	   flash[:success] = "顧客情報を更新しました。"
 	   redirect_to admins_customer_path(@customer)
	 else
	   render 'edit'
	 end
  end

  	private
  	def customer_params
  		params.require(:customer).permit(:last_name,:first_name,
  								:last_name_kana,:first_name_kana,
  								:postal_number,:address,
  								:phone_number,:email)
  	end
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  def top
  	# @orders = Orders.all
  end
end

app/controllers/admins/item_genres_controller.rb
class Admins::ItemGenresController < ApplicationController
  def index
    @item_genre = ItemGenre.new
    @item_genres = ItemGenre.all
  end
  
  def create
    @item_genre = ItemGenre.new(item_genre_params)
    if @item_genre.save
      # binding.pry
      redirect_to admins_item_genres_path, notice: 'ジャンルを登録しました'
    else
      @item_genres = ItemGenre.all
      render :index
    end
  end

  def edit
    @item_genre = ItemGenre.find(params[:id])
  end

  def update
    @item_genre = ItemGenre.find(params[:id])
    if @item_genre.update(item_genre_params)
      redirect_to admins_item_genres_path, notice: 'ジャンルを編集しました'
    else
      render :edit
    end
  end

  private
    def item_genre_params
      params.require(:item_genre).permit(:name,:is_delete)
    end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @item_genres = ItemGenre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_item_path(@item), notice: "商品を登録しました"
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @tax = @item.price * 1.1
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_item_path(@item), notice: "商品を更新しました"
    else
      render :edit
    end
  end


  private
    def item_params
      params.require(:item).permit(:image, :name, :description, :item_genre_id, :price, :is_active)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  #サインイン後、どこの画面に遷移するのかを設定する必要がある。
  #上記と同じく、サインアウト後のridirect先を設定する必要がある。

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_number, :address, :phone_number])
    #sign_up（新規会員登録）の際に必要なカラムを追加。
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path(@customer), notice: "登録情報を編集しました"
    else
      render :edit
    end
  end

  def exit
    @customer = Customer.find(params[:id])
  end

  def destroy
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_number, :address, :phone_number)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
	end
end

app/controllers/shipping_addresses_controller.rb
class ShippingAddressesController < ApplicationController
  def index
  	@customer = Customer.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/item_genres_helper.rb
module Admins::ItemGenresHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/admins/customers/edit.html.erb
<!-- 修正項目 -->
<!-- エラーが出たときにフォームのレイアウトが崩れる -->

<!-- エラーメッセージ -->
<% if @customer.errors.any? %>
	<div>
		<div class="alert alert-danger">
			The form contents <%= pluralize(@customer.errors.count, "error") %>
		</div>
		<ul>
			<% @customer.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<h1><%= @customer.last_name + @customer.first_name %>の会員情報編集</h1>


<%= form_with model: [:admins,@customer], local: true do |f| %>
	<div class="form-group col-md-10 col-md-offset-1">

		<div class="control-label col-sm-2">会員ID: <%= @customer.id %></div>

		<%= f.label :氏名, class: "control-label col-sm-2"%>
		<%= f.text_field :last_name %>
		<%= f.text_field :first_name %></br>

		<%= f.label :フリガナ, class: "control-label col-sm-2" %>
		<%= f.text_field :last_name_kana %>
		<%= f.text_field :first_name_kana %></br>

		<%= f.label :郵便番号, class: "control-label col-sm-2" %>
		<%= f.text_field :postal_number %></br>

		<%= f.label :住所, class: "control-label col-sm-2" %>
		<%= f.text_field :address, class: "col-sm-9" %></br>

		<%= f.label :電話番号, class: "control-label col-sm-2" %>
		<%= f.text_field :phone_number, class: "col-sm-3" %></br>

		<%= f.label :メールアドレス, class: "control-label col-sm-2" %>
		<%= f.text_field :email, class: "col-sm-3" %></br>

		<%= f.label :会員ステータス, class: "control-label col-sm-2"%>

		<%= f.radio_button :is_delete, :true %>
		<%= f.label :is_delete, "有効", style: "display: inline-block" %>

		<%= f.radio_button :is_delete, :false %>
		<%= f.label :is_delete, "退会済み", style: "display: inline-block"  %></br>

		<%= f.submit "変更を保存する", class: "btn btn-primary col-sm-2" %>
	</div>
<% end %>

app/views/admins/customers/index.html.erb
<h1>会員一覧</h1>
<table class="table">
	<thead>
		<tr>
			<th>会員ID</th>
			<th>氏名</th>
			<th>メールアドレス</th>
			<th>ステータス</th>
		</tr>
	</thead>
	<% @customers.each do |customer| %>
		<tbody>
			<tr>
				<!-- 会員ID -->
				<th><%= customer.id %></th>
				<!-- 氏名 -->
				<th><%= link_to customer.last_name+customer.first_name, admins_customer_path(customer) %></th>
				<!-- メールアドレス -->
				<th><%= customer.email %></th>
				<!-- 会員ステータス -->
				<th><%= customer.is_delete ? '有効' : '退会済' %></th>
			</tr>
		</tbody>
	<% end %>
</table>

app/views/admins/customers/show.html.erb
<!-- 修正項目 -->


<!-- サクセスメッセージ -->
<%= flash[:success] %>


<h1><%= @customer.last_name+@customer.first_name %>さんの会員詳細</h1>

顧客ID : <%= @customer.id %> <%= @customer.is_delete ? '有効会員' : '退会済み会員' %></br>

氏名 : <%= @customer.last_name + " " +@customer.first_name %></br>

フリガナ : <%= @customer.last_name + " " +@customer.first_name %></br>

郵便番号 : <%= @customer.postal_number %></br>

住所 : <%= @customer.address %></br>

電話番号 : <%=@customer.phone_number %></br>

メールアドレス : <%= @customer.email %></br>

<%= link_to "編集する", edit_admins_customer_path, class: "btn btn-primary" %>

<%= link_to "注文履歴一覧を見る", "#", class: "btn btn-primary" %>

app/views/admins/items/edit.html.erb
<!--⭐︎訂正項目⭐︎-->
<!--ジャンルと販売ステータスのformの幅が気になる、、-->


<div class="container">
  <h3 class="col-lg-4 text-center">商品編集</h3><br><br><br><br>

<!--==========⭐商品編集⭐︎==========-->
  
  <%= form_for(@item, url:admins_item_path(@item.id)) do |f| %>

    <!--エラー文-->
    <% if @item.errors.any? %>
      <div class="alert alert-warning">
        <ul>
          <% @item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">

      <!--画像-->
      <div class="col-lg-4 text-center">
        <%= attachment_image_tag @item, :image, format: 'jpeg', size: "300x200", fallback: "no_image.jpg" %><br><br>
        <%= f.attachment_field :image, class: "user-edit-form" %><br>
      </div>

      <div class="col-lg-8">

        <!--商品名-->
        <div class="form-group">
          <%= f.label :name, "商品名", class: "col-lg-2 align-top" %>
          <%= f.text_field :name, class: "col-lg-4" %><br>
        </div>

        <!--説明-->
        <div class="form-group">
          <%= f.label :description, "商品説明", class: "col-lg-2 align-top" %>
          <%= f.text_area :description, rows: 5, class: "col-lg-4" %><br>
        </div>

        <!--ジャンル-->
        <div class="form-group">
          <%= f.label :item_genre_id, "ジャンル", class: "col-lg-2 align-top" %>
          <%= f.select :item_genre_id, ItemGenre.all.map{|o| [o.name, o.id]}, class: "col-lg-4" %><br>
        </div>

        <!--税抜価格-->
        <div class="form-group">
          <%= f.label :price, "税抜価格", class: "col-lg-2 align-top" %>
          <%= f.text_field :price, class: "col-lg-4" %>円<br>
        </div>

        <!--販売ステータス-->
        <div class="form-group">
          <%= f.label :is_active, "販売ステータス", class: "col-lg-2 align-top" %>
          <%= f.select :is_active, [['販売中', 'true'], ['販売停止中', 'false']], class: "col-lg-4" %><br>
        </div>

        <!--変更ボタン-->
        <div class="text-right">
          <%= f.submit "変更を保存", class: "btn btn-primary"%>
        </div>

      </div>
    </div>
  <% end %>
</div>

app/views/admins/items/index.html.erb
<!--==========⭐商品一覧⭐︎==========-->

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="col-lg-4 text-center">商品一覧</h3>

      <!--新規登録画面に遷移-->
      <h4 class="text-right"><%= link_to "＋", new_admins_item_path %></h4>

      <!--商品一覧-->
      <table class="table">

        <thead class="thead-light">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <% @items.each do |item| %>
        <tbody>
          <tr>
            <!--ID-->
            <td><%= item.id %></td>
            <!--商品名-->
            <td><%= link_to item.name, admins_item_path(item) %></td>
            <!--価格-->
            <td><%= item.price %></td>
            <!--ジャンル-->
            <td><%= item.item_genre.name %></td>
            <!--ステータス-->
            <td><%= item.is_active ? "販売中" : "販売停止中" %></td>
          </tr>
        </tbody>

        <% end %>
      </table>

      <div class="pagination">
        <%= paginate @items %>
      </div>
    </div>
  </div>
</div>

app/views/admins/items/new.html.erb
<!--⭐︎訂正項目⭐︎-->
<!--ジャンルと販売ステータスのformの幅が気になる、、-->


<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="col-lg-4 text-center">商品新規登録</h3><br><br><br><br>

<!--==========⭐商品新規登録⭐︎==========-->

      <%= form_for(@item, url:admins_items_path) do |f| %>

        <!--エラー文-->
        <% if @item.errors.any? %>
          <div class="alert alert-warning">
            <ul>
              <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="row">

          <!--画像-->
          <div class="col-lg-4 text-center">
            <%= attachment_image_tag @item, :image, format: 'jpeg', size: "300x200", fallback: "no_image.jpg" %><br><br>
            <%= f.attachment_field :image, class: "" %><br>
          </div>

          <div class="col-lg-8">

            <!--商品名-->
            <div class="form-group">
              <%= f.label :name, "商品名", class: "col-lg-2 align-top" %>
              <%= f.text_field :name, class: "col-lg-4" %><br>
            </div>

            <!--説明-->
            <div class="form-group">
              <%= f.label :description, "商品説明", class: "col-lg-2 align-top" %>
              <%= f.text_area :description, rows: 5, class: "col-lg-4" %><br>
            </div>

            <!--ジャンル-->
            <div class="form-group">
              <%= f.label :item_genre_id, "ジャンル", class: "col-lg-2 align-top" %>
              <%= f.select :item_genre_id, ItemGenre.all.map{|o| [o.name, o.id]}, include_blank: '--選択してください--', class: "col-lg-4" %><br>
            </div>

            <!--税抜価格-->
            <div class="form-group">
              <%= f.label :price, "税抜価格", class: "col-lg-2 align-top" %>
              <%= f.text_field :price, class: "col-lg-4" %>円<br>
            </div>

            <!--販売ステータス-->
            <div class="form-group">
              <%= f.label :is_active, "販売ステータス", class: "col-lg-2 align-top" %>
              <%= f.select :is_active, [['販売中', 'true'], ['販売停止中', 'false']], include_blank: '--選択してください--', selected: '--選択してください--', class: "col-lg-4" %><br>
            </div>

            <!--変更ボタン-->
            <div class="text-right">
              <%= f.submit "新規登録", class: "btn btn-primary"%>
            </div>

          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/items/show.html.erb
<!--==========⭐商品詳細⭐==========-->
<div class="container">
  <h3 class="col-lg-4 text-center">商品詳細</h3><br><br><br><br>

  <div class="row">

    <!--画像-->
    <div class="col-lg-4 text-center">
      <%= attachment_image_tag @item, :image, format: 'jpeg', size: "300x200", fallback: "no_image.jpg" %>
    </div>
    <br>

    <div class="col-lg-8">

      <!--商品名-->
      商品名　　　<%= @item.name %><br><br>

      <!--商品説明-->
      商品説明　　<%= @item.description %><br><br>

      <!--ジャンル-->
      ジャンル　　<%= @item.item_genre.name %><br><br>

      <!--価格-->
      税込価格（税抜価格）　　<%= @item.price %>（<%= @tax.to_i %>） 円<br><br>

      <!--ステータス-->
      販売ステータス　　<%= @item.is_active ? "販売中" : "販売停止中" %><br><br>

      <!--編集リンク-->
      <div class="text-right">
        <%= link_to '編集する', edit_admins_item_path, class: "btn btn-primary" %>
      </div>

    </div>
  </div>
</div>

app/views/customers/edit.html.erb
edit画面だよ。
カラムについては完成したかな。
後はビジュアルを整えれば大丈夫かと。
完成までもうちょっと待っててね。
<h2>登録情報編集</h2>

<%= form_for(@customer) do |f| %>

<!-- エラーメッセージ表示-->
<% if @customer.errors.any? %>
	<h3><%= @customer.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @customer.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<table>
    <thead>
      <tr>
        <td>名前</td>
        <td>
          <div class="field">
            <%= f.label :last_name, "（姓）" %>
            <%= f.text_field :last_name, autofocus: true, class: "last_name" %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label :first_name, "（名）" %>
            <%= f.text_field :first_name, autofocus: true, class: "first_name" %>
          </div>
        </td>
      </tr>

      <tr>
        <td>フリガナ</td>
        <td>
          <div class="field">
            <%= f.label :last_name_kana, "（セイ）" %>
            <%= f.text_field :last_name_kana, autofocus: true, class: "last_name_kana" %>
          </div>
        </td>
        <td>
          <div class="field">
            <%= f.label :first_name_kana, "（メイ）" %>
            <%= f.text_field :first_name_kana, autofocus: true, class: "first_name_kana" %>
          </div>
        </td>
      </tr>
    </thead>
  </table>

  <div class="field">
    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :postal_number, "郵便番号（ハイフンなし）" %>
    <%= f.text_field :postal_number, autofocus: true, autocomplete: "postal_number" %>
  </div>

  <div class="field">
    <%= f.label :address, "住所" %>
    <%= f.text_field :address, autofocus: true, autocomplete: "address" %>
  </div>

  <div class="field">
    <%= f.label :phone_number, "電話番号（ハイフンなし）" %>
    <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number" %>
  </div>

  <div class="actions">
    <%= f.submit "編集内容を保存する" %>
  </div>
<% end %>

<%= link_to "退会する(routing未設定)", customer_path %>

app/views/customers/exit.html.erb
退会画面だよ。作成中だよ。
完成までもうちょっと待っててね。
<h2>本当に退会しますか？</h2>
<h3>退会すると、会員登録情報や<br>
これまでの購入履歴が閲覧できなくなります。<br>
退会する場合は、「退会する」をクリックしてください。<br>
</h3>
<%= link_to "退会しない", customer_path %>
<%= link_to '退会する', %>

app/views/customers/show.html.erb
マイページだよ。リンクは飛べたり飛べなかったりするよ。ビジュアルも整えないとね。完成までもうちょっと待っててね。
<h2>マイページ</h2>
<table>
  <thead>
  	<tr>
  	  <td>登録情報</td>
  	  <td>
  	  	<%= link_to "編集する", edit_customer_path %>
  	  </td>
  	  <td><%= link_to 'パスワードを変更する' %></td>
  	</tr>
  </thead>
  <tbody>
  	<tr>
  	  <td>氏名</td>
  	  <td>
  	  	<%= @customer.last_name %>
        <%= @customer.first_name %>
  	  </td>
  	</tr>
  	<tr>
  	  <td>カナ</td>
  	  <td>
  	    <%= @customer.last_name_kana %>
        <%= @customer.first_name_kana %>
      </td>
  	</tr>
  	<tr>
  	  <td>郵便番号</td>
  	  <td><%= @customer.postal_number %></td>
  	</tr>
  	<tr>
  	  <td>住所</td>
  	  <td><%= @customer.address %></td>
  	</tr>
  	<tr>
  	  <td>電話番号</td>
  	  <td><%= @customer.phone_number %></td>
  	</tr>
  	<tr>
  	  <td>メールアドレス</td>
  	  <td><%= @customer.email %></td>
  	</tr>
  </tbody>
  <tfoot>
  	<tr>
  	  <td>発送先</td>
  	  <td><%= link_to "一覧を見る" %></td>
  	</tr>
  	<tr>
  	  <td>注文履歴</td>
  	  <td><%= link_to '一覧を見る' %></td>
  	</tr>
  </tfoot>
</table>

app/views/items/index.html.erb
<!-- 訳あってindexとshowを取り替えました -->

<div class="container" style="margin-top:20px;">
<div class="row">

	<nav class="col-lg-2" style="background-color: #f0f8ff;">
		<table>
			<thead>
				<tr>
					<th>ジャンル検索</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>ケーキ</td>
				</tr>
				<tr>
					<td>焼き菓子</td>
				</tr>
				<tr>
					<td>プリン</td>
				</tr>
				<tr>
					<td>キャンディ</td>
				</tr>
			</tbody>
		</table>
	</nav>


	<main class="col-lg-10" style="background-color: #f0f0f0">
		<div class="row">
			<h5>商品一覧(全xxxx件)</h5>
		</div>
		
		<div class="row">
			<div class="col-lg-3">	
					<!-- ここにeach文を差し込めばOK -->

<!-- 
				<%= @items.each do |item| %>
					<%#= link_to item_path(item.id) %>
						<%= attachment_image_tag item, :image, format: 'jpeg', size: "300x200", fallback: "no_image.jpg" %>
					<%# end %>
					<%= item.name %>
					<%= item.price %>
				<% end %>-->



				<% @items.each do |item| %>
              <%= link_to item_path(item) do %>
                <%= attachment_image_tag item, :image, format: 'jpeg', size: "300x200", fallback: "no_image.jpg" %>
              <% end %>
							<%= item.name %>
              ¥ <%= item.price %>
        <% end %>
			</div>
		</div>		<!-- rowの閉じタグ -->
</div>		<!-- containerの閉じタグ -->

app/views/items/show.html.erb
<!-- 訳あってindexとshowを取り替えました -->

<div class="container" style="margin-top:20px;">
<div class="row">

	<nav class="col-lg-2" style="background-color: #f0f8ff;">
		<table>
			<thead>
				<tr>
					<th>ジャンル検索</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>ケーキ</td>
				</tr>
				<tr>
					<td>焼き菓子</td>
				</tr>
				<tr>
					<td>プリン</td>
				</tr>
				<tr>
					<td>キャンディ</td>
				</tr>
			</tbody>
		</table>
	</nav>


	<main class="col-lg-10" style="background-color: #fffafa">
		<div class="row">
			<div class="col">
				<%= attachment_image_tag @item, :image, format: 'jpeg', size: "300x200", fallback: "no_image.jpg" %>
			</div>
			<div class="col">
				<%= @item.name %>
				<%= @item.description %>
				<%= @item.price %>
				<% form_for @item do |f|%>
					<%= f.select :count, [[1, 1], [2, 2], [3, 3]], include_blank: '個数選択', selected: '個数選択' %>
					<%= f.submit "カートに入れる" %>
				<% end %>
				<div class="btn-group">
					<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
					個数選択
					<span class="caret"></span>
					</button>
					<ul class="dropdown-menu" role="menu">
						<li>1</li>
						<li>1</li>
						<li>1</li>
					</ul>
				</div>

				<div class="btn btn-primary">カートに入れる</div>
			</div>
		</div>
	</main>

</div>		<!-- rowの閉じタグ -->
</div>		<!-- containerの閉じタグ -->