config/routes.rb
Rails.application.routes.draw do
  get 'cart_items/index'
  devise_for :customers
  devise_for :admins
  namespace :admins do
  	root 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :item_genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items
  resources :customers, only: [:show, :edit, :update, :exit, :destroy] 
  resources :shipping_addresses, only:[:index, :edit, :update, :destroy]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shipping_addresses, dependent: :destroy

  validates :address, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_number, presence: true
  validates :phone_number, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :item_genre
  attachment :image

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :item_genre_id, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: { in: [true, false] }
end

app/models/item_genre.rb
class ItemGenre < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  #真偽値の存在をチェックしたい場合には以下を記述
  validates :is_delete, inclusion: { in: [true, false] }

  has_many :items
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  def top
  	# @orders = Orders.all
  end
end

app/controllers/admins/item_genres_controller.rb
class Admins::ItemGenresController < ApplicationController
  def index
    @item_genre = ItemGenre.new
    @item_genres = ItemGenre.all
  end
  
  def create
    @item_genre = ItemGenre.new(item_genre_params)
    if @item_genre.save
      # binding.pry
      redirect_to admins_item_genres_path, notice: 'ジャンルを登録しました'
    else
      @item_genres = ItemGenre.all
      render :index
    end
  end

  def edit
    @item_genre = ItemGenre.find(params[:id])
  end

  def update
    @item_genre = ItemGenre.find(params[:id])
    if @item_genre.update(item_genre_params)
      redirect_to admins_item_genres_path, notice: 'ジャンルを編集しました'
    else
      render :edit
    end
  end

  private
    def item_genre_params
      params.require(:item_genre).permit(:name,:is_delete)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  #サインイン後、どこの画面に遷移するのかを設定する必要がある。
  #上記と同じく、サインアウト後のridirect先を設定する必要がある。

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_number, :address, :phone_number])
    #sign_up（新規会員登録）の際に必要なカラムを追加。
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path(@customer), notice: "登録情報を編集しました"
    else
      render :edit
    end
  end

  def exit
    @customer = Customer.find(params[:id])
  end

  def destroy
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_number, :address, :phone_number)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
	end
end

app/controllers/shipping_addresses_controller.rb
class ShippingAddressesController < ApplicationController
  def index
  	@customer = Customer.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/item_genres_helper.rb
module Admins::ItemGenresHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/admins/item_genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3>ジャンル編集</h3><br><br>

<!--==========⭐ジャンル追加⭐==========-->

      <%= form_for(@item_genre, url: admins_item_genre_path(@item_genre.id)) do |f| %>

        <!--エラー文-->
        <% if @item_genre.errors.any? %>
          <div class="alert alert-warning">
            <ul>
              <% @item_genre.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <!--ジャンル名-->
        <%= f.label :name, "ジャンル", class: "mr-3" %>
        <%= f.text_field :name, autofocus: true, class: "mr-3" %>

        <!--有効無効-->
        <%= f.radio_button :is_delete, false, checked: true %>
        <%= f.label :is_delete, "有効", class: "mr-3" %>
        <%= f.radio_button :is_delete, true %>
        <%= f.label :is_delete, "無効", class: "mr-3" %>

        <!--追加ボタン-->
        <%= f.submit "変更を保存する", class: "btn btn-primary"%>

      <% end %>
    </div>
  </div>
</div>

app/views/admins/item_genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3>ジャンル一覧・追加</h3><br><br>

<!--==========⭐ジャンル追加⭐==========-->
      <%= form_for(@item_genre, url: admins_item_genres_path) do |f| %>

        <!--エラー文-->
        <% if @item_genre.errors.any? %>
          <div class="alert alert-warning">
            <ul>
              <% @item_genre.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <!--ジャンル名-->
        <%= f.label :name, "ジャンル", class: "mr-3" %>
        <%= f.text_field :name, autofocus: true, class: "mr-3" %>

        <!--有効無効-->
        <%= f.radio_button :is_delete, false, checked: true %>
        <%= f.label :is_delete, "有効", class: "mr-3" %>
        <%= f.radio_button :is_delete, true %>
        <%= f.label :is_delete, "無効", class: "mr-3" %>

        <!--追加ボタン-->
        <%= f.submit "追加", class: "btn btn-primary" %>

      <% end %>
    </div>
  </div>
  <br>
  <br>


<!--==========⭐ジャンル一覧⭐==========-->
  <div class="row">
    <div class="col-lg-6">

      <table class="table">

        <thead class="thead-light">
          <tr>
            <th>ジャンル</th>
            <th>状態</th>
            <th></th>
          </tr>
        </thead>

        <% @item_genres.each do |genre| %>
        <tbody>
          <tr>
            <td><%= genre.name %></td>
            <td><%= genre.is_delete ? '無効' : '有効' %></td>
            <td class="text-center"><%= link_to '編集する', edit_admins_item_genre_path(genre.id), class: "btn btn-primary" %></td>
          </tr>
        </tbody>

        <% end %>
      </table>

    </div>
  </div>
</div>