config/routes.rb
Rails.application.routes.draw do
  get 'cart_items/index'
  devise_for :customers
  devise_for :admins
  namespace :admins do
  	root 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :item_genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items
  resources :customers, only: [:show, :edit, :update, :exit, :destroy] 
  resources :shipping_addresses, only:[:index, :edit, :update, :destroy]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shipping_addresses, dependent: :destroy

  validates :address, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_number, presence: true
  validates :phone_number, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :item_genre
  attachment :image

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :item_genre_id, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: { in: [true, false] }
end

app/models/item_genre.rb
class ItemGenre < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  #真偽値の存在をチェックしたい場合には以下を記述
  validates :is_delete, inclusion: { in: [true, false] }

  has_many :items
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  #サインイン後、どこの画面に遷移するのかを設定する必要がある。
  #上記と同じく、サインアウト後のridirect先を設定する必要がある。

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_number, :address, :phone_number])
    #sign_up（新規会員登録）の際に必要なカラムを追加。
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path(@customer), notice: "登録情報を編集しました"
    else
      render :edit
    end
  end

  def exit
    @customer = Customer.find(params[:id])
  end

  def destroy
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_number, :address, :phone_number)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
	end
end

app/controllers/shipping_addresses_controller.rb
class ShippingAddressesController < ApplicationController
  def index
  	@customer = Customer.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!--ヘッダーの記述-->
    <header class="navbar navbar-fixed-top navbar-inverse" style="background:#E95464;">
      <div class="container-fluid">

        <!-- ヘッダー左 -->
        <nav class="bar-left">
          <%= link_to 'NaganoCake' %>
        </nav>


        <!-- ヘッダー中 -->
        <nav class="bar-center">
          <p>ようこそ、xxxさん</p>
        </nav>


        <!-- ヘッダー右 -->
        <!-- CTM:マイページ商品一覧カート新規登録ログインログアウト ADM: 商品一覧会員一覧注文履歴一覧ジャンル一覧ログインログアウト検索 -->

        <nav class="bar-right">
          <ul style="margin:0; padding: 0">
            <li><%= link_to 'マイページ' %></li>
            <li><%= link_to '商品一覧', items_path %></li>
            <li><%= link_to 'カート' %></li>
            <li><%= link_to '新規登録' %></li>
            <li><%= link_to 'ログイン' %></li>
            <li><%= link_to 'ログアウト' %></li>
          </ul>
        </nav>

<!------------------※一時的に表示（admin）------------------>
        <nav class="bar-right">
          <ul style="margin:0; padding: 0">
            <li><%= link_to '商品一覧', admins_items_path %></li>
            <li><%= link_to '会員一覧', admins_customers_path %></li>
            <li><%= link_to '注文履歴一覧' %></li>
            <li><%= link_to 'ジャンル一覧', admins_item_genres_path %></li>
            <li><%= link_to 'ログアウト' %></li>
          </ul>
        </nav>

      </div>
    </header>

      <%= yield %>

  </body>
</html>